name: pysm

channels:
    - conda-forge

dependencies:
    - python=3.6
    - numba
    - astropy=3.2
    - healpy
    - matplotlib
    - toml
    - pandoc
    - ipykernel
    - pip
    - sphinx-math-dollar
    - pip:
        - sphinx-astropy
        - nbsphinx
