name: pysm

channels:
    - astropy
    - conda-forge

dependencies:
    - python>=3.5
    - numba
    - h5py
    - astropy
    - Cython
    - matplotlib
    - healpy
    - numpy
    - configobj
    - pip:
        - sphinx-astropy
