name: pysm

channels:
    - conda-forge

dependencies:
    - python>=3.5
    - numba
    - astropy
    - healpy
    - matplotlib
    - toml
    - pandoc
    - ipykernel
    - pip:
        - sphinx-astropy
        - nbsphinx
