[tool.poetry]
name = "pysm3"
version = "3.2.1.dev"
description = ""
authors = ["Andrea Zonca <code@andreazonca.com>"]

[tool.poetry.dependencies]
python = "^3.6"
healpy = "^1.13.0"
numba = "^0.49.1"
toml = "^0.10.1"
astropy = "^4.0.1"
sphinx = {version = "^3.0.4", optional = true, extras = ["docs"]}
sphinx-astropy = {version = "^1.3", optional = true, extras = ["docs"]}
nbsphinx = {version = "^0.7.0", optional = true, extras = ["docs"]}
sphinx-math-dollar = {version = "^1.1.1", optional = true, extras = ["docs"]}
pandoc = {version = "^1.0.2", optional = true, extras = ["docs"]}
ipykernel = {version = "^5.3.0", optional = true, extras = ["docs"]}

[tool.poetry.dev-dependencies]
tox = "^3.15.1"
mpi4py = "^3.0.3"
pytest-astropy = "^0.8.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
